#!/usr/bin/env bash

# generate_stack_type.bash
# Marek Filip <xfilip46>
# Implementace překladače imperativního jazyka IFJ20.
# 26/11/2020

# Usage:
# Script requires two arguments to work properly
# 1st arg: data type name to use for the stack implementation.
# 2nd arg: folder, into which to place the created files.

if [ -z "$1" ] || [ -z "$2" ]; then
	echo "Usage: generate_stack_type <TYPE> <DIR> [TYPE_INCLUDE]"
	echo "TYPE: Data type name to use for the stack implementation."
	echo "DIR: Folder, into which to place the created files."
	echo "TYPE_INCLUDE: Additional include that needs to be present for the TYPE."
	exit 1
fi

# make other args into an array
args=("${@:3}")
# prepend each argument with #include
if [[ -n "$args" ]]; then
	OPT_INCLUDES=$(printf "#include \"%s\"\n" "${args[@]}")
	OPT_INCLUDES=$(printf "\n// includes defining the TYPE\n$OPT_INCLUDES")$'\n'
fi

readonly date=$(date '+%d/%m/%Y')
readonly TYPE=$1
PTRTYPE=$1
readonly DIR=$2

# is pointer is present
if echo "$TYPE" | grep '*' >/dev/null; then
	# replace every "*" with "ptr"
	PTRTYPE=$(echo "$TYPE" | sed "s/*/ptr/g")
	TYPEDEF="typedef $TYPE $PTRTYPE"
	TYPEDEF_STMT="$TYPEDEF;"
	TYPEDEF_DEF="#define TYPEDEF $TYPEDEF"
	TYPEDEF_ALL="\n// typedef to handle pointers\n$TYPEDEF_STMT\n$TYPEDEF_DEF\n"
	TYPEDEF_UNDEF="\n#undef TYPEDEF  // undefine the TYPEDEF, has been already used in stack.h"
fi

# create stack_type.c
printf "/**
 * @file stack_$PTRTYPE.c
 * @author Marek Filip <xfilip46>
 * @brief $TYPE stack source file.
 * @details Implementace překladače imperativního jazyka IFJ20.
 * Generated by generate_stack_type.bash (Author: Marek Filip <xfilip46>)
 * @date $date
 */

#include \"stack_$PTRTYPE.h\"

#define TYPE $PTRTYPE

// due to how C includes work we can safely include extern definitions
// from a header file
#include \"stack_extern_template.h\"

#undef TYPE
" > "$DIR/stack_$PTRTYPE.c"

# create stack_type.h
printf "/**
 * @file stack_$PTRTYPE.h
 * @author Marek Filip <xfilip46>
 * @brief $TYPE stack header file.
 * @details Implementace překladače imperativního jazyka IFJ20.
 * Generated by generate_stack_type.bash (Author: Marek Filip <xfilip46>)
 * @date $date
 */
$OPT_INCLUDES$TYPEDEF_ALL
#define TYPE $PTRTYPE

// external header guards for stack.h
#ifndef __STACK_"$PTRTYPE"_H__
#define __STACK_"$PTRTYPE"_H__
#include \"stack.h\"  // this is the main file
#endif

#undef TYPE  // will be defined again in the stack_$PTRTYPE.h$TYPEDEF_UNDEF
" > "$DIR/stack_$PTRTYPE.h"
