/**
 * @file stack_token_t.c
 * @author Marek Filip <xfilip46>
 * @brief token_t stack source file.
 * @details Implementace překladače imperativního jazyka IFJ20.
 * Generated by generate_stack_type.bash (Author: Marek Filip <xfilip46>)
 * @date 04/12/2020
 */

#include "stack_token_t.h"

#define TYPE token_t

// due to how C includes work we can safely include extern definitions
// from a header file
#include "stack_extern_template.h"

#undef TYPE
