/**
 * @file stack_token_t.h
 * @author Marek Filip <xfilip46>
 * @brief token_t stack header file.
 * @details Implementace překladače imperativního jazyka IFJ20.
 * Generated by generate_stack_type.bash (Author: Marek Filip <xfilip46>)
 * @date 04/12/2020
 */

// includes defining the TYPE
#include "token.h"

#define TYPE token_t

// external header guards for stack.h
#ifndef __STACK_token_t_H__
#define __STACK_token_t_H__
#include "stack.h"  // this is the main file
#endif

#undef TYPE  // will be defined again in the stack_token_t.h
