/**
 * @file stack_int.h
 * @author Marek Filip <xfilip46>
 * @brief int stack header file.
 * @details Implementace překladače imperativního jazyka IFJ20.
 * Generated by generate_stack_type.bash (Author: Marek Filip <xfilip46>)
 * @date 28/11/2020
 */

#define TYPE int

// external header guards for stack.h
#ifndef __STACK_int_H__
#define __STACK_int_H__
#include "stack.h"  // this is the main file
#endif

#undef TYPE  // will be defined again in the stack_int.h
