/**
 * @file stack_stack.h
 * @author Marek Filip <xfilip46>
 * @brief stack stack header file.
 * @details Implementace překladače imperativního jazyka IFJ20.
 * Generated by generate_stack_type.bash (Author: Marek Filip <xfilip46>)
 * @date 27/11/2020
 */

// header guards included in stack.h, no need for them here

;
#define TYPEDEF 
#define TYPE stack  // undef is located in the stack_stack.c file
#include "stack.h"
