/**
 * @file stack_int.h
 * @author Marek Filip <xfilip46>
 * @brief int stack header file.
 * @details Implementace překladače imperativního jazyka IFJ20.
 * Generated by generate_stack_type.bash (Author: Marek Filip <xfilip46>)
 * @date 26/11/2020
 */

// header guards included in stack.h, no need for them here

#define TYPE int  // undef is located in the stack_int.c file
#include "stack.h"
