/**
 * @file stack_charptr.h
 * @author Marek Filip <xfilip46>
 * @brief char* stack header file.
 * @details Implementace překladače imperativního jazyka IFJ20.
 * Generated by generate_stack_type.bash (Author: Marek Filip <xfilip46>)
 * @date 27/11/2020
 */

// header guards included in stack.h, no need for them here

typedef char* charptr;
#define TYPEDEF typedef char* charptr
#define TYPE charptr  // undef is located in the stack_charptr.c file
#include "stack.h"
