/**
 * @file stack_stack_charptr_tptr.c
 * @author Marek Filip <xfilip46>
 * @brief stack_charptr_t* stack source file.
 * @details Implementace překladače imperativního jazyka IFJ20.
 * Generated by generate_stack_type.bash (Author: Marek Filip <xfilip46>)
 * @date 28/11/2020
 */

#include "stack_stack_charptr_tptr.h"

#define TYPE stack_charptr_tptr

// due to how C includes work we can safely include extern definitions
// from a header file
#include "stack_extern_template.h"

#undef TYPE
