/**
 * @file stack_func_call_t.c
 * @author Marek Filip <xfilip46>
 * @brief func_call_t stack source file.
 * @details Implementace překladače imperativního jazyka IFJ20.
 * Generated by generate_stack_type.bash (Author: Marek Filip <xfilip46>)
 * @date 08/12/2020
 */

#include "stack_func_call_t.h"

#define TYPE func_call_t

// due to how C includes work we can safely include extern definitions
// from a header file
#include "stack_extern_template.h"

#undef TYPE
