/**
 * @file stack_charptr.h
 * @author Marek Filip <xfilip46>
 * @brief char* stack header file.
 * @details Implementace překladače imperativního jazyka IFJ20.
 * Generated by generate_stack_type.bash (Author: Marek Filip <xfilip46>)
 * @date 28/11/2020
 */

// typedef to handle pointers
typedef char* charptr;
#define TYPEDEF typedef char* charptr

#define TYPE charptr

// external header guards for stack.h
#ifndef __STACK_charptr_H__
#define __STACK_charptr_H__
#include "stack.h"  // this is the main file
#endif

#undef TYPE  // will be defined again in the stack_charptr.h
#undef TYPEDEF  // undefine the TYPEDEF, has been already used in stack.h
