/**
 * @file stack_stack_charptr_t.h
 * @author Marek Filip <xfilip46>
 * @brief stack_charptr_t stack header file.
 * @details Implementace překladače imperativního jazyka IFJ20.
 * Generated by generate_stack_type.bash (Author: Marek Filip <xfilip46>)
 * @date 27/11/2020
 */

// header guards included in stack.h, no need for them here

;
#define TYPEDEF 
#define TYPE stack_charptr_t  // undef is located in the stack_stack_charptr_t.c file
#include "stack.h"
