/**
 * @file stack_stack_charptr_tptr.h
 * @author Marek Filip <xfilip46>
 * @brief stack_charptr_t* stack header file.
 * @details Implementace překladače imperativního jazyka IFJ20.
 * Generated by generate_stack_type.bash (Author: Marek Filip <xfilip46>)
 * @date 28/11/2020
 */

// includes defining the TYPE
#include "stack_charptr.h"

// typedef to handle pointers
typedef stack_charptr_t* stack_charptr_tptr;
#define TYPEDEF typedef stack_charptr_t* stack_charptr_tptr

#define TYPE stack_charptr_tptr

// external header guards for stack.h
#ifndef __STACK_stack_charptr_tptr_H__
#define __STACK_stack_charptr_tptr_H__
#include "stack.h"  // this is the main file
#endif

#undef TYPE  // will be defined again in the stack_stack_charptr_tptr.h
#undef TYPEDEF  // undefine the TYPEDEF, has been already used in stack.h
